### ISSUE TITLE
In-place and create-new options for append-pdf

### ISSUE THREAD

**Issue by douglascrp** [ntmcminn/alfresco-pdf-toolkit#11]
@ntmcminn How are you?

Are you considering to implement those options for the append-pdf action?
That one would be nice.

Thank you

**Comment by ntmcminn** [comment]
Yes, putting the inplace option together now.

**Comment by douglascrp** [comment]
Great. Thank you

**Comment by ntmcminn** [comment]
ok, in-place option is in append action:

https://github.com/ntmcminn/alfresco-pdf-toolkit/commit/44d0215049b9f4d400ef55af7cb231598696cf2b

create new node behavior can be controlled globally with this setting:

pdftoolkit.createNew=true

I'd like to make that overideable in the action parameters as well, adding it to my todo list.
