### ISSUE TITLE
Digital signature location params missing from dialog and action

### ISSUE THREAD

**Issue by jpotts** [ntmcminn/alfresco-pdf-toolkit#12]
I am having trouble getting a digital signature to visibly appear on the PDF. The PDF is getting signed, which I've confirmed by opening the document in Acrobat, but the watermark isn't in place.

In troubleshooting this I'm noticing that the signPDF method of PDFToolkitServiceImpl looks for an X and Y location which it uses to make a digital signature visible, but those two params are not passed in via the PDFSignatureActionExecuter. The action executer has a single location param, but nothing for X and Y specifically. The "sign document" dialog in Share also lacks X & Y fields.

I think older versions of the add-on had fields for X & Y so I'm wondering if they were removed on purpose or if this is a bug.

Is the add-on in its current state expected to produce a visible digital signature watermark?

**Comment by ntmcminn** [comment]
Sounds like a bug to me.  Will investigate ASAP

On Monday, December 7, 2015, Jeff Potts <notifications@github.com> wrote:

> I am having trouble getting a digital signature to visibly appear on the
> PDF. The PDF is getting signed, which I've confirmed by opening the
> document in Acrobat, but the watermark isn't in place.
>
> In troubleshooting this I'm noticing that the signPDF method of
> PDFToolkitServiceImpl looks for an X and Y location which it uses to make a
> digital signature visible, but those two params are not passed in via the
> PDFSignatureActionExecuter. The action executer has a single location
> param, but nothing for X and Y specifically. The "sign document" dialog in
> Share also lacks X & Y fields.
>
> I think older versions of the add-on had fields for X & Y so I'm wondering
> if they were removed on purpose or if this is a bug.
>
> Is the add-on in its current state expected to produce a visible digital
> signature watermark?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntmcminn/alfresco-pdf-toolkit/issues/12>.
>


-- 
Nathan T. McMinn
http://nathanmcminn.com
http://www.linkedin.com/in/nathantmcminn

**Comment by jpotts** [comment]
Further update: The X & Y params are in the action because they get inherited from BasePDFStampActionExecuter. But they are missing from the dialog. So, to test whether or not the action can create a visible signature, I'm using JavaScript. When I do that, I am seeing an "invalid page number: 0" message that appears to be coming from itext.

**Comment by ntmcminn** [comment]
Can you send me the stack trace?

**Comment by ntmcminn** [comment]
I don't think the x/y params are ever actually used in the signature action, need to look at the code to confirm.

**Comment by jpotts** [comment]
I think the problem with this was I was specifying page number as an integer. In any case I'm happily seeing my digital signature stamps now so let's close this. Stay tuned for a PR that adds some page number checking.
