### ISSUE TITLE
Adding more than one digital signature invalidates existing digital signatures

### ISSUE THREAD

**Issue by jpotts** [ntmcminn/alfresco-pdf-toolkit#16]
Adding one digital signature to a document works great. But when you try to add an additional digital signature you will invalidate all previous digital signatures.

I have created PR #15 which addresses that problem by using the append flag when calling PdfStamper.createSignature. The default will be to always append because I couldn't think of a good reason not to append. If you want to use the old behavior, pass "new-revision" equal to false when invoking the action.

**Comment by ntmcminn** [comment]
Ack, merged this PR a while ago, forgot to close issue.
