### ISSUE TITLE
AMP files

### ISSUE THREAD

**Issue by mdragatsis** [ntmcminn/alfresco-pdf-toolkit#20]
Could someone please help me? I downloaded the alfresco-pdf-toolkit but can not fine the amp files. Di I create them? what is the process?   Kind regards.

**Comment by chris001** [comment]
You can download the amp files here.
https://github.com/ntmcminn/alfresco-pdf-toolkit/releases

**Comment by mdragatsis** [comment]
Thank you Chris! How are they created from the zip file? I apologize for my "newness".

**Comment by chris001** [comment]
An AMP file is just a ZIP file with a required structure of folders and certain required files.

I believe that to make AMP files easily and conveniently, from the zip you downloaded from github containing the code (and css, images, etc), you'd best use a developer app, for example the excellent Eclipse, plus the Apache Maven plugin, which is able to build an AMP file for you, using the "Maven Alfresco AMP archetype".

See more here:

https://wiki.alfresco.com/wiki/AMP_Files

This might also be interesting to you.  About building WAR (java web application archive) files with Eclipse and Maven.

http://crunchify.com/how-to-create-a-war-file-from-eclipse-using-maven-plugin-apache-maven-war-plugin-usage/

**Comment by mdragatsis** [comment]
Thank you again Chris! I was able to get the amp from your last link. It
looks like it's working as documented.

**Comment by ntmcminn** [comment]
Chris, thanks for helping resolve this problem!  Closing the issue.
