### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by mdragatsis** [ntmcminn/alfresco-pdf-toolkit#21]
Anyone has an idea on why I get this error when running the apply_amps.bat file? Using Alfresco 5.1 community edition. 

02140000 An IO error was encountered during deployment of the AMP into the WAR

**Comment by douglascrp** [comment]
OS level permission maybe?
Do you have permission to write the war files?

Em seg, 14 de mar de 2016 19:00, mdragatsis <notifications@github.com>
escreveu:

> Anyone has an idea on why I get this error when running the apply_amps.bat
> file?
>
> 02140000 An IO error was encountered during deployment of the AMP into the
> WAR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntmcminn/alfresco-pdf-toolkit/issues/21>.
>
-- 

Douglas C. R. Paes

**Comment by mdragatsis** [comment]
What way would you recommend verifying that I can write to the war file?

**Comment by mdragatsis** [comment]
You were correct. I ran CMD as admin and it worked fine.

**Comment by ntmcminn** [comment]
Great, thanks for helping out Douglas!  Closing the issue.

**Comment by MonsieurGed** [comment]
Bonjour, 
J'ai le même problème en essayant d'installer Gobernance service sur ACS 6.2.1, avec ce message: 

D:\Alfresco> java -jar bin\alfresco-mmt.jar install amps\alfresco-governance-services-enterprise-repo-3.3.0.1.amp tomcat\webapps\alfresco.war
04170000 An IO error was encountered during deployment of the AMP into the WAR. 

Le passage en mode super Administrateur n'a rien changé.

Pouvez-vous m'aider s'il vous plait?

**Comment by MonsieurGed** [comment]
Problème résolu ! J'avais pas assez d'espace sur mon disque D:\
