### ISSUE TITLE
Split action form when setting the action to execute in a folder rule

### ISSUE THREAD

**Issue by douglascrp** [ntmcminn/alfresco-pdf-toolkit#26]
The form for the split action is broken when used to define a folder rule.

The **Destination folder** parameter has not object picker control, but a normal text box and there are 2 check boxes for the **Execute in place** parameter.

**Comment by ntmcminn** [comment]
That's correct, and that problem will affect the form display on folder rule create / edit for all of the actions.  Unfortunately Alfresco doesn't provide a proper public API (yet) for customizing the forms used when defining a folder rule.  I'm going to try to get this extension certified, which means it can only use defined public APIs.  If you want to use the PDF toolkit from a folder rule, I suggest you use the script action, and call some server side JS to execute the PDF toolkit action.

**Comment by douglascrp** [comment]
That's exactly what I usually do, I use javascript code to call the pdf toolkit actions.
I just wanted to let you know about the problem.

Thank you for your answer.
