### ISSUE TITLE
Watermark PDF to a new location not working

### ISSUE THREAD

**Issue by sujaypillai** [ntmcminn/alfresco-pdf-toolkit#3]
The new watermarked PDF document isn't created at the specified destination. Rather it executes in place and watermarks the pdf on which the doclib action is executed.

Alfresco (Enterprise). Current version: 4.2.2 (.3 r73878-b57) schema 6,056.

**Comment by ntmcminn** [comment]
Fixed in 321d7118322a82aca8b99ced087a9489645ad33b, will be included in 1.3 Beta2 release
