### ISSUE TITLE
Merge PDF fails in alfresco share community edition

### ISSUE THREAD

**Issue by ZanderWT** [ntmcminn/alfresco-pdf-toolkit#6]
We're having this issue on Alfresco Community 4.2.f while using alfresco-pdf-toolkit 1.0.0. The problem also exists in alfresco-pdf-toolkit 1.1.1-beta1

Steps to reproduce:
1.  Browse to a PDF document in a site on Alfresco Share and click "Merge PDF Document" under Document Actions.
2. Select a valid Destination Folder and a different PDF document to append to. Fill in The Destination name and click OK

Observe error dialog "Failure: The merge operation failed". The merged PDF Document is not created.

**Comment by ntmcminn** [comment]
Fixed in last batch of commits, will be in version 1.3 Beta2
