### ISSUE TITLE
Transform .doc our .docx to pdf action

### ISSUE THREAD

**Issue by Dnhatsave** [ntmcminn/alfresco-pdf-toolkit#63]
Hi @douglascrp ,

Its is possible to set the transform/convert option on the previewed document to permit user convert .doc ou .docx documents to .pdf without download it our create an folder rule ??

**Comment by douglascrp** [comment]
Sorry, but I didn't get the idea.

Transforming doc and docx into pdf is already the default behaviour, as the preview is using the pdf rendition to present the content to the user.

Can you elaborate?

**Comment by Dnhatsave** [comment]
the ideia is create an action on side menu of the document previewed to allow users "convert and raplace" the corrent version of the document to pdf.

**Comment by douglascrp** [comment]
Now I understood.
But as this has nothing to do with this project, I have to ask you to post your question at https://hub.alfresco.com/, as this is not an issue with the project.
There you will find more people able to help you with the required work to achieve what you need.

I am closing this issue.

**Comment by Dnhatsave** [comment]
ok,
thanks for the advice.
