### ISSUE TITLE
Extract pages from pdf 

### ISSUE THREAD

**Issue by akashdubey251996** [ntmcminn/alfresco-pdf-toolkit#66]
I have installed this addon on docker installed alfresco 6.2 . While performing the extract pages from pdf it is giving error:
     **The extract operation failed**

Except this all options are working fine

**Comment by akashdubey251996** [comment]
it is solved

**Comment by chris001** [comment]
@akashdubey251996 
How did you solve it?
List the steps you took?!

**Comment by akashdubey251996** [comment]
> @akashdubey251996
> How did you solve it?
> List the steps you took?!

I installed again for docker installed alfresco 6.2 and it worked.
