### ISSUE TITLE
I am not able to run this add-on on Alfresco community edition 5.0

### ISSUE THREAD

**Issue by anubioinfo** [ntmcminn/alfresco-pdf-toolkit#9]
I have tried to run the pdf-toolkit on Alfresco community edition 5.0,but unable to do so. Can you help me to run it on the same.

Regards,
Anurag

**Comment by jottley** [comment]
Can you provide any log files, js console error messages, etc.

**Comment by anubioinfo** [comment]
I am not getting the any error on console. But no button is getting displayed on any option selection related to pdf toolkit. Please let me know what could we the issue. I am attaching the screenshot.

![pdf-toolkit-issue](https://cloud.githubusercontent.com/assets/10369900/6243898/50940160-b771-11e4-9657-66ed89661a16.png)

**Comment by anubioinfo** [comment]
This was the issue in version 5. But after installing 4 the same issue is coming.

**Comment by anubioinfo** [comment]
I am not getting any issue in log. I am downloading the .amp files from google code as that is clear to me how to install.

I have downloaded the github code but not sure how to integrate github version of pdf-toolkit. Thats why installed the amp from google code.

Let me know if that is fine.

**Comment by anubioinfo** [comment]
Dear jottley,

I have resolved the issue. Now I am able to see the buttons. 
Please let me know how I can configure pdf merge as everytime I am getting the error 'The merge operation failed'. I am attaching the screen shot.

Regards,
Anurag
![screenshot from 2015-02-18 17 04 45](https://cloud.githubusercontent.com/assets/10369900/6246597/cfe5c704-b790-11e4-90c8-e079164dfc0f.png)

**Comment by anubioinfo** [comment]
When I select the file during merge pdf it shows 'Not a valid nodeRef: 'null://null/null'' in the file selection box. Attching the screenshot.

Please help me.

Regards,
Anurag
![merge_file_selection_issue](https://cloud.githubusercontent.com/assets/10369900/6246697/db177612-b791-11e4-932e-3ebc3fee878b.png)

**Comment by jottley** [comment]
You should be able to grab the amps from https://github.com/ntmcminn/alfresco-pdf-toolkit/releases for the latest code.  That is the first place I would start.  Once those are in place we can start to look at the other issues.  When you  were able to get things to work ... were you modifying the code/config to make it work?

**Comment by anubioinfo** [comment]
Dear Jottley,

I have installed the software and tested merge, split, encrypt etc. On file level it is working fine but when I try to create rule on directory level it is giving issue for merge pdf.
It shows 'Not a valid nodeRef: 'null://null/null'' in the file selection box. Attching the screenshot.
![merge_pdf_issue_during_rule_creation](https://cloud.githubusercontent.com/assets/10369900/6264729/8bfc4eca-b84c-11e4-8ee5-2d8f9bacc7b5.png)

**Comment by anubioinfo** [comment]
Dear Jottley,

Can you guide me that how can I debug this issue.

Regards,
Anurag

**Comment by anubioinfo** [comment]
Dear Jottley,

I am stuck at a point. I am creating custom aspect for additional meta data capture. It works fine until I install pdf toolkit but as soon as I install pdf toolkit the custom aspect label disappers from aspect list.

Please suggest me.

Regards,
Anurag

**Comment by ntmcminn** [comment]
There's a new release coming soon, this module hasn't been fully updated
for Alfresco 5.  It's likely that something has changed in the rules
javascript, and the extension is breaking.  I'll take a look.

On Tue, Feb 24, 2015 at 7:36 AM, anubioinfo <notifications@github.com>
wrote:

> Dear Jottley,
>
> I am stuck at a point. I am creating custom aspect for additional meta
> data capture. It works fine until I install pdf toolkit but as soon as I
> install pdf toolkit the custom aspect label disappers from aspect list.
>
> Please suggest me.
>
> Regards,
> Anurag
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntmcminn/alfresco-pdf-toolkit/issues/9#issuecomment-75756814>
> .
>



-- 
Nathan T. McMinn
http://www.unorganizedmachines.com
http://www.linkedin.com/in/nathantmcminn

**Comment by ntmcminn** [comment]
We have to remove the rule creation form changes.  That is not a proper extension point in Alfresco, and was a nasty hack.  For now, you would be best off using a script action to call some JS from a content rule.  That JS can then call the action using the usual Javascript action APIs.
